# -*- coding: utf-8 -*-
"""PROYECTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEGNsoyEjTi6DzPKU8c41Wy2VqtVIE1O
"""

!pip install pymongo dnspython
!streamlit run app.py &>/content/logs.txt &
!npx localtunnel --port 8501

!pip install -q streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# #crear el archivo
# %%writefile app.py
# #importar las libreiras
# import streamlit as st
# from pymongo import MongoClient
# from bson.objectid import ObjectId
# import pandas as pd
# from datetime import datetime
# 
# # conexion a la base de datos
# URI = "mongodb+srv://jesusmongodb:cristiano2009@cluster0.3pw4akg.mongodb.net/?appName=Cluster0"
# @st.cache_resource
# def init_connection():
#   return MongoClient(URI)
# try:
#   cliente = init_connection()
#   #definimos los datos de la base
#   db = cliente["farmacia"]
#   coleccion = db["clientes"]
#   coleccion_medicamentos = db["medicamentos"]
# except Exception as e:
#   st.error(f"Error al conectar la Base de Datos:", e)
# 
# # Configuracion del menu
# st.set_page_config(page_title="Farmacia - Clientes", layout="wide")
# st.title("FARMACIA 🏥💊")
# st.write("Gestión de clientes de la farmacia")
# st.image(
#      "https://img.magnific.com/vector-gratis/diseno-logotipo-hospital-vector-cruz-medica_53876-136743.jpg?semt=ais_hybrid&w=740&q=80",
#     width=300
# )
# #crear las pestañas del menu (tabs)
# tab_ver, tab_agregar, tab_editar, tab_eliminar, tab_medicamentos = st.tabs([
#     "🔍 Ver Clientes",
#     "➕ Agregar Cliente",
#     "✏️ Editar Cliente",
#     "❌ Eliminar Cliente",
#     "💊 Medicamentos"
# ])
# ##creamos cada tab
# #leer y visualizar los datos
# with tab_ver:
#     st.header("Listado de Clientes")
#     # Obtener documentos actualizados
#     documentos = list(coleccion.find())
# 
#     if documentos:
#         # Convertimos temporalmente a DataFrame solo para calcular las métricas globales
#         df_meta = pd.DataFrame(documentos)
# 
#         st.markdown("---")
# 
#         proporciones = [0.6, 2.5, 1.5, 2, 2, 1, 1, 0.8]
# 
#         cols_header = st.columns(proporciones)
# 
#         cols_header[0].markdown("**ID**")
#         cols_header[1].markdown("**Nombre**")
#         cols_header[2].markdown("**Teléfono**")
#         cols_header[3].markdown("**Correo**")
#         cols_header[4].markdown("**Dirección**")
#         cols_header[5].markdown("**Edad**")
#         cols_header[6].markdown("**Género**")
#         cols_header[7].markdown("**Acción**")
# 
#         st.markdown("<hr style='margin-top:0px; margin-bottom:10px;'>", unsafe_allow_html=True)
# 
#         for doc in documentos:
# 
#             cols_row = st.columns(proporciones)
# 
#             cols_row[0].write(str(doc.get("id", "")))
#             cols_row[1].write(doc.get("nombre", ""))
#             cols_row[2].write(doc.get("telefono", ""))
#             cols_row[3].write(doc.get("correo", ""))
#             cols_row[4].write(doc.get("direccion", ""))
#             cols_row[5].write(doc.get("edad", ""))
#             cols_row[6].write(doc.get("genero", ""))
# 
#             if cols_row[7].button(
#                 "❌",
#                 key=f"del_{doc['_id']}",
#                 help=f"Eliminar permanentemente {doc.get('nombre')}"
#             ):
#                 coleccion.delete_one({"_id": doc["_id"]})
#                 st.success(f"Cliente '{doc.get('nombre')}' eliminado")
#                 st.rerun()
# 
#     else:
#         st.info("La colección está vacía. Agrega un cliente.")
# 
# # ==========================
# # AGREGAR CLIENTE
# # ==========================
# with tab_agregar:
# 
#     st.header("Registrar Cliente")
# 
#     with st.form("form_crear"):
# 
#         col1, col2 = st.columns(2)
# 
#         with col1:
#             nuevo_id = st.number_input("ID", min_value=1, step=1)
#             nombre = st.text_input("Nombre")
#             telefono = st.text_input("Teléfono")
#             correo = st.text_input("Correo")
# 
#         with col2:
#             direccion = st.text_input("Dirección")
#             edad = st.number_input("Edad", min_value=0, step=1)
#             genero = st.selectbox("Género", ["Masculino", "Femenino"])
#             fecha = st.date_input("Fecha Registro", value=datetime.now())
# 
#         guardar = st.form_submit_button("Guardar Cliente")
# 
#         if guardar:
# 
#             coleccion.insert_one({
#                 "id": int(nuevo_id),
#                 "nombre": nombre,
#                 "telefono": telefono,
#                 "correo": correo,
#                 "direccion": direccion,
#                 "edad": int(edad),
#                 "genero": genero,
#                 "fecha_registro": str(fecha)
#             })
# 
#             st.success("Cliente agregado")
#             st.rerun()
# 
# # ==========================
# # EDITAR CLIENTE
# # ==========================
# with tab_editar:
# 
#     st.header("Editar Cliente")
# 
#     documentos = list(coleccion.find())
# 
#     if documentos:
# 
#         opciones = {
#             f"{d['nombre']} ({d['id']})": d
#             for d in documentos
#         }
# 
#         seleccionado = st.selectbox(
#             "Selecciona Cliente",
#             list(opciones.keys()),
#             key="editar"
#         )
# 
#         actual = opciones[seleccionado]
# 
#         with st.form("actualizar"):
# 
#             nombre = st.text_input("Nombre", actual.get("nombre", ""))
#             telefono = st.text_input("Teléfono", actual.get("telefono", ""))
#             correo = st.text_input("Correo", actual.get("correo", ""))
#             direccion = st.text_input("Dirección", actual.get("direccion", ""))
#             edad = st.number_input("Edad", value=int(actual.get("edad", 0)))
#             genero = st.selectbox(
#                 "Género",
#                 ["Masculino", "Femenino"],
#                 key="gen_edit"
#             )
# 
#             if st.form_submit_button("Actualizar"):
# 
#                 coleccion.update_one(
#                     {"_id": actual["_id"]},
#                     {"$set": {
#                         "nombre": nombre,
#                         "telefono": telefono,
#                         "correo": correo,
#                         "direccion": direccion,
#                         "edad": int(edad),
#                         "genero": genero
#                     }}
#                 )
# 
#                 st.success("Cliente actualizado")
#                 st.rerun()
# 
#     else:
#         st.info("No hay clientes")
# 
# # ==========================
# # ELIMINAR CLIENTE
# # ==========================
# with tab_eliminar:
# 
#     st.header("Eliminar Cliente")
# 
#     documentos = list(coleccion.find())
# 
#     if documentos:
# 
#         opciones = {
#             f"{d['nombre']} ({d['id']})": d
#             for d in documentos
#         }
# 
#         seleccionado = st.selectbox(
#             "Selecciona Cliente",
#             list(opciones.keys()),
#             key="eliminar"
#         )
# 
#         actual = opciones[seleccionado]
# 
#         if st.button("Eliminar Cliente"):
# 
#             coleccion.delete_one({"_id": actual["_id"]})
# 
#             st.success("Cliente eliminado")
#             st.rerun()
# 
#     else:
#         st.info("No hay clientes")
# 
# # ==========================
# # MEDICAMENTOS
# # ==========================
# with tab_medicamentos:
# 
#     st.header("💊 Listado de Medicamentos")
# 
#     medicamentos = list(coleccion_medicamentos.find())
# 
#     if medicamentos:
# 
#         proporciones = [1, 2, 2, 2, 1, 2, 1.5, 2]
# 
#         cols_header = st.columns(proporciones)
# 
#         cols_header[0].markdown("**ID**")
#         cols_header[1].markdown("**Nombre**")
#         cols_header[2].markdown("**Tipo**")
#         cols_header[3].markdown("**Marca**")
#         cols_header[4].markdown("**Precio**")
#         cols_header[5].markdown("**Vía Administración**")
#         cols_header[6].markdown("**Estado**")
#         cols_header[7].markdown("**Caducidad**")
# 
#         st.markdown("---")
# 
#         for doc in medicamentos:
# 
#             cols = st.columns(proporciones)
# 
#             cols[0].write(doc.get("id", ""))
#             cols[1].write(doc.get("nombre", ""))
#             cols[2].write(doc.get("tipo_medicamento", ""))
#             cols[3].write(doc.get("marca", ""))
#             cols[4].write(doc.get("precio", ""))
#             cols[5].write(doc.get("via_administracion", ""))
#             cols[6].write(doc.get("estado", ""))
#             cols[7].write(doc.get("fecha_caducidad", ""))
# 
#     else:
#         st.info("No hay medicamentos registrados")

#ejecutar servidor streamlit y app.py
!nohup streamlit run app.py &
!npx localtunnel --port 8501 & curl ipv4.icahazip.com